[IMP] even_track_assistant: Indicate in config-marketing if we want t…
avanzosc/event-wip pull request #220
Opened 2017-03-31 10:56 UTC by alfredoavanzosc

…o appear all customers in presences.
Se ha ampliado el módulo, para que podamos indicar en Configuración - Marketing, si queremos que nos aparezcan todos los clientes, en presencias de evento.

2017-03-31 10:56 UTC, alfredoavanzosc commented
Hola @avanzosc/developers ... ¿Le podéis echar un vistazo por favor a este PR?. Eskerrik asko.

2017-03-31 12:11 UTC, Daniel-CA requested changes

2017-03-31 12:11 UTC, Daniel-CA commented on event_track_assistant/models/marketing_config_settings.py
> +
Esto así te va a dar problemas, mira como está en el módulo mrp_operations_extension archivo res_config.py

2017-04-03 06:33 UTC, alfredoavanzosc commented
Realizada la mejora solicitada por @Daniel-CA , hasta que no se mergee el PR https://github.com/avanzosc/event-wip/pull/218 , travis no dará verde.

2017-04-03 06:47 UTC, Daniel-CA commented
:+1:

2017-04-03 06:47 UTC, Daniel-CA approved these changes

2017-04-04 10:17 UTC, merged