[FIX] calendar_holiday: Fix error when recalculate employee calendar.
avanzosc/event-wip pull request #233
Opened 2017-04-24 09:39 UTC by alfredoavanzosc

Corregir BUG al recalcular el calendario de un empleado.

2017-04-24 12:54 UTC, anajuaristi requested changes

2017-04-24 12:54 UTC, anajuaristi commented on calendar_holiday/tests/test_calendar_holiday.py
> +        wiz.button_calculate_workables_and_festives()
Alfredo... se está haciendo la llamada 2 veces aquí. Supongo que es un error

2017-04-25 08:14 UTC, alfredoavanzosc commented
Egunon @avanzosc/developers .. ¿le podéis echar un vistazo por favor a este módulo?. Eskerrik asko.

2017-04-25 08:28 UTC, anajuaristi approved these changes

2017-04-25 08:30 UTC, merged