[IMP] event_registration_sepa: New field "Validate exists mandate" in…
avanzosc/event-wip pull request #259
Opened 2017-06-23 10:51 UTC by alfredoavanzosc

… Payment mode" object.
Nuevo campo "Validar existe mandato" en el objeto "Modo de Pago", para que a la hora de validar un registro de evento, se le pida el mandado sepa o no al alumno registrado.

2017-06-27 14:55 UTC, alfredoavanzosc commented
@avanzosc/developers ... ¿le podéis echar por favor un vistazo a este PR?. Eskerrik asko.

2017-06-27 15:56 UTC, Daniel-CA requested changes

2017-06-27 15:56 UTC, Daniel-CA commented on event_registration_sepa/models/event.py
>                  _('%s needs a valid sepa mandate for confirm the assistant!')
En le readme deberías explicar que es un mandato valido

2017-06-27 16:01 UTC, mikelarre reviewed
:+1:

2017-06-27 19:01 UTC, oihane commented on event_registration_sepa/models/payment_mode.py
> +        string='Validate exists mandate', default=True)
No debería de ser por defecto verdadero

2017-06-28 06:07 UTC, alfredoavanzosc commented on event_registration_sepa/models/payment_mode.py
> +        string='Validate exists mandate', default=True)
Egunon @Oihane, según lo solicitado por @anajuaristi , por defecto debe de tener el valor de verdadero. Eskerrik asko.

2017-06-30 08:48 UTC, agaldona approved these changes

2017-06-30 08:54 UTC, Daniel-CA commented on event_registration_sepa/README.rst
> +* You can confirm an assistant if the student or its parent has a valid sepa
assistant es asistente, debería ser attendance

2017-07-04 08:07 UTC, Daniel-CA approved these changes

2017-07-04 08:07 UTC, merged