[ADD] event_track_presence_customer_info: Customer adress, zip, and c…
avanzosc/event-wip pull request #260
Opened 2017-06-27 10:13 UTC by alfredoavanzosc

…ity info, in event track presences.
Nuevo módulo para llevar información del cliente del pedido de venta, a las presencias de las sesiones.

2017-06-27 11:39 UTC, alfredoavanzosc commented
@avanzosc/developers ... ¿le podéis echar un vistazo a este nuevo módulo?. Eskerrik asko.

2017-06-27 14:56 UTC, mikelarre reviewed
:+1:

2017-06-27 16:01 UTC, Daniel-CA requested changes

2017-06-27 16:01 UTC, Daniel-CA commented on event_track_presence_customer_info/models/event.py
> +                      presence.customer_id.stree2 or False)
Si la calle es una concatenación de los dos campos deberían ir los dos, no solo el primero.
Aparte el campo se llama street2

2017-06-28 06:33 UTC, alfredoavanzosc commented on event_track_presence_customer_info/models/event.py
> +                      presence.customer_id.stree2 or False)
Realizada la mejora solicitada por @Daniel-CA , y subido el módulo. Eskerrik asko.

2017-06-28 09:10 UTC, Daniel-CA approved these changes

2017-06-30 08:46 UTC, agaldona approved these changes

2017-07-05 12:01 UTC, closed without merging