[IMP] event_registration_analytic: When create claim from presence im…
avanzosc/event-wip pull request #88
Opened 2016-09-16 10:04 UTC by alfredoavanzosc

…putation, charge "student" or "teacher" category in claim.
Cuando se crea una reclamación al imputar tiempos en presencias, cargar la categoría "estudiante", o la categoría "profesor" en la reclamación.

2016-09-16 10:53 UTC, alfredoavanzosc commented
@agaldona , @Daniel-CA , @esthermm . ¿Le podéis echar un vistazo por favor a la modificación?

2016-09-16 11:15 UTC, agaldona commented
:+1:

2016-09-16 12:00 UTC, oihane commented on event_registration_analytic/wizard/wiz_impute_in_presence_from_session.py
> +        claim_vals['categ_id'] = self.env.ref(
claim_vals['categ_id'] = self.env.ref('event_registration_analytic.crm_case_categ_teacher').id if line.employee else self.env.ref('event_registration_analytic.crm_case_categ_student').id

2016-09-16 12:05 UTC, oihane requested changes

2016-09-19 11:09 UTC, alfredoavanzosc commented
Realizadas las mejoras de programación solicitadas por @oihane , y subido el módulo.

2016-09-19 12:46 UTC, Daniel-CA commented
:+1:

2016-09-19 13:20 UTC, oihane approved these changes

2016-09-19 14:03 UTC, merged