[ADD] event_registration_sepa: new module
avanzosc/event-wip pull request #93
Opened 2016-10-04 10:36 UTC by esthermm

2016-10-18 11:26 UTC, esthermm commented
@agaldona @Daniel-CA @oihane @mikelarre @alfredoavanzosc review pls, he cambiado el travis para poder testear correctamente el módulo. A ver que os parece

2016-10-24 16:34 UTC, oihane commented
@esthermm este modulo no es compatible con el event_track_assistant y debería de serlo. Estoy haciendo cambios en aquel para que aun no siendo dependientes no fallen al instalar ambos.

2016-10-24 16:41 UTC, oihane requested changes

2016-10-24 16:41 UTC, oihane commented on event_registration_sepa/models/event.py
> +            partner_id = record.partner_id.parent_id or record.partner_id
Porque no sacas los mandatos sepa:
```python
mandates = partner_is.mapped('bank_ids.mandate_ids').filtered(
    lambda x: x.format == 'sepa')
```
 y luego filtras por valid o draft??

Aunque no lo hicieses así el mapped debe incluir el bank_ids porque puede tener más de un banco

2016-10-25 09:06 UTC, esthermm commented
@oihane cambios solicitados hechos y rebase

2016-10-25 09:44 UTC, oihane approved these changes

2016-10-25 09:45 UTC, oihane commented
me surge la duda de si no dará problemas en el caso de "profesores", el módulo en base está correcto, estoy pensando en el caso del cliente.

2016-10-25 10:47 UTC, agaldona commented
:+1:

2016-10-25 15:56 UTC, acysos commented
Estamos haciendo otro módulo que tiene una funcionalidad que creo que es similar, sino he entendido mal este generá ordenes de giro sepa y el nuestro crea facturas intermedias para luego girar. Aunque la facturación se basa en una serie de reglas, como si no se acude al curso y se ha facturado ya el un porcentaje X no se factura... Además de crear las facturas de proveedor si el profesor es autonomo. Espero subir la alpha hoy mismo como un PR.

2016-10-26 07:52 UTC, oihane commented
Este modulo lo que hace es únicamente validar que quien se "registra" en un evento tiene un mandato de sepa valido. La facturación se hace en otro módulo, pero no te sé explicar exactamente como lo hace.

2016-10-27 13:02 UTC, mikelarre commented
:+1:

2016-10-27 13:13 UTC, merged